Homework/Homework/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('todo_list/', include('todo_list.urls'))
]

Homework/home/urls.py
from django.urls import path
from home import views

app_name='home'
urlpatterns = [
    # http://127.0.0.1:8000/
    path('', views.index)
]

Homework/todo_list/urls.py
from django.urls import path
from todo_list import views

app_name='todo_list'
urlpatterns = [
    # http://127.0.0.1:8000/todo_list/
    path('', views.index, name='index'),
    path('delete/<int:id>', views.delete, name='delete'),
    path('task_complete/<int:id>', views.task_complete, name='task_complete'),
]

Homework/home/models.py
from django.db import models

# Create your models here.

Homework/todo_list/models.py
from django.db import models
from datetime import datetime
# Create your models here.
class toDoList(models.Model):
    todo_id = models.AutoField(primary_key=True)
    completed = models.BooleanField(default=False)
    todo = models.CharField(max_length=50)
    last_update = models.DateTimeField(default=datetime.now())

    class Meta:
        db_table = 'todo_list'

Homework/home/views.py
from django.shortcuts import render

# Create your views here.
def index(request):

    return render(request,'home/index.html')

Homework/todo_list/views.py
from django.shortcuts import render, redirect
from .models import toDoList
# Create your views here.
def index(request):
    thingsToDo = toDoList.objects.all()
    if request.method =='POST':
        things = request.POST.get('someThing')
        toDoList.objects.create(
            todo = things
        ) 
        return redirect('todo_list:index')
    return render(request,'todo_list/index.html', {'lists':thingsToDo})

def delete(request, id):   
    things = toDoList.objects.get(todo_id=id)  
    things.delete()
    return redirect('todo_list:index')

def task_complete(request, id):
    if request.method == 'POST':
        task = toDoList.objects.get(todo_id=id)
        completed_value = request.POST.get('completed') == 'true'
        task.completed = completed_value
        task.save()
    return redirect('todo_list:index')

Homework/home/templates/home/index.html
{% extends 'base.html' %} {% block title %}
<h3>Home Page</h3>
{% endblock %} {% block content %}

<h3>Hello Django！！</h3>
{% endblock %}

Homework/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% load static %}
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Bootstrap demo</title>
    <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous"> -->
    <link rel="stylesheet" href="{% static 'styles/bootstrap.min.css' %}" />
    {% block styles %} {% endblock %}
  </head>
  <body>
    <div class="container">
      <div class="row mt-3">
        {% include 'navbar.html' %}
        <div class="col-2" style="background-color: LightSkyBlue"></div>
        <div class="col-8">
          <div class="card">
            <h5 class="card-header">{{ title|default:"Django App" }}</h5>
            <div class="card-body">
              {% block content %}
              <p>這裡的內容會被換掉</p>
              {% endblock %}
            </div>
          </div>
        </div>
        <div class="col-2" style="background-color: lightgray"></div>
      </div>
      {% include 'footer.html' %}
    </div>

    <!-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script> -->
    <script src="{% static 'scripts/bootstrap.min.js' %}"></script>
    {% block scripts %} {% endblock %}
  </body>
</html>

Homework/templates/footer.html
<footer class="py-3 my-4">
    <ul class="nav justify-content-center border-bottom pb-3 mb-3">
      <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Home</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Features</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Pricing</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">FAQs</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">About</a></li>
    </ul>
    <p class="text-center text-body-secondary">© 2024 Company, Inc</p>
  </footer>

Homework/templates/index.html
<!DOCTYPE html>
<html lang="zh-hant-TW">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h2>專案的 Index Page</h2>
</body>
</html>

Homework/templates/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">
      <img
        src="{% static 'images/Logos.png' %}"
        alt="Bootstrap"
        width="50"
        height="24"
      />
    </a>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarNav"
      aria-controls="navbarNav"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <!-- <a class="nav-link active" aria-current="page" href="/">Home</a> -->
          <a class="nav-link active" aria-current="page" href="">Home</a>
        </li>
        <li class="nav-item">
          <!-- <a class="nav-link active" aria-current="page" href="/store/">Store</a> -->
          <a class="nav-link active" aria-current="page" href="">Store</a>
        </li>
        <li class="nav-item">
          <!-- <a class="nav-link" href="/store/about/">about</a> -->
          <a class="nav-link" href="">nothing</a>
        </li>
        <li class="nav-item">
          <!-- <a class="nav-link" href="/store/show/">show</a> -->
          <a class="nav-link" href="">nothing</a>
        </li>
        <li class="nav-item">
          <!-- <a class="nav-link" href="/store/abc/ ">abc</a> -->
          <a class="nav-link" href="">nothing</a>
        </li>
        <li class="nav-item">
          <!-- <a class="nav-link" href="/store/abc/ ">abc</a> -->
          <a class="nav-link" href="">nothing</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

Homework/todo_list/templates/todo_list/index.html
{% extends 'base.html' %} {% block content %}
<h2>To Do List</h2>
<form method="POST">
  {% csrf_token %}
  <div class="mb-3">
    <label for="someThing" class="form-label">
      <input
        type="text"
        name="someThing"
        class="form-control"
        id="someThing"
        placeholder="請輸入代辦事項"
      />
    </label>
    <button type="submit" class="btn btn-primary">送出</button>
  </div>
</form>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>狀態</th>
      <th>代辦事項</th>
      <th>編輯</th>
    </tr>
  </thead>
  <tbody>
    {% for things in lists %}
    <tr>
      <td>
        <form
          method="POST"
          action="{% url 'todo_list:task_complete' things.todo_id %}"
          style="display: inline"
        >
          {% csrf_token %}
          <input
            type="checkbox"
            name="completed"
            value="true"
            {% if things.completed %} 
              checked 
            {% endif %}
            onchange="this.form.submit()"
          />
          {% if things.completed %}
          <span>已完成</span>
          {% else %}
          <span>未完成</span>
          {% endif %}
        </form>
      </td>
      <td>{{ things.todo }}</td>
      <td>
        <a
          href="{% url 'todo_list:delete' things.todo_id %}"
          class="btn btn-danger"
          >刪除</a
        >
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}